apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: secure-topic-writer
  labels:
    strimzi.io/cluster: amqs-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example Producer Acls for topic lines
      - resource:
          type: topic
          name: lines
          patternType: literal
        operation: Write
        host: "*"