apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: lines
  labels:
    strimzi.io/cluster: amqs-cluster
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 14400000
    segment.bytes: 1073741824